// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXF7Hk3dMUmZba3m9UWJ0sDXs3vgSJ65c',
    appId: '1:383435628942:web:2f680f157fbf8a608244df',
    messagingSenderId: '383435628942',
    projectId: 'authentication-a4bc6',
    authDomain: 'authentication-a4bc6.firebaseapp.com',
    storageBucket: 'authentication-a4bc6.firebasestorage.app',
    measurementId: 'G-K3DF4Z2S8T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuNaKIBuxOS4vJzzujf4STqSV6clTt_wA',
    appId: '1:383435628942:android:fa577ef761d094178244df',
    messagingSenderId: '383435628942',
    projectId: 'authentication-a4bc6',
    storageBucket: 'authentication-a4bc6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCptUf3LvLZ50HNkhtyIPnHEoEG7PtFuVc',
    appId: '1:383435628942:ios:ed0a6ed1e3b95f178244df',
    messagingSenderId: '383435628942',
    projectId: 'authentication-a4bc6',
    storageBucket: 'authentication-a4bc6.firebasestorage.app',
    androidClientId: '383435628942-doaamvhra73nbf0sues9gdbaej29h7k6.apps.googleusercontent.com',
    iosClientId: '383435628942-r2eoo9168sf2n8cjggqd6jitffnf36vi.apps.googleusercontent.com',
    iosBundleId: 'com.example.mechinetest1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCptUf3LvLZ50HNkhtyIPnHEoEG7PtFuVc',
    appId: '1:383435628942:ios:ed0a6ed1e3b95f178244df',
    messagingSenderId: '383435628942',
    projectId: 'authentication-a4bc6',
    storageBucket: 'authentication-a4bc6.firebasestorage.app',
    androidClientId: '383435628942-doaamvhra73nbf0sues9gdbaej29h7k6.apps.googleusercontent.com',
    iosClientId: '383435628942-r2eoo9168sf2n8cjggqd6jitffnf36vi.apps.googleusercontent.com',
    iosBundleId: 'com.example.mechinetest1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXF7Hk3dMUmZba3m9UWJ0sDXs3vgSJ65c',
    appId: '1:383435628942:web:85994714ff119e018244df',
    messagingSenderId: '383435628942',
    projectId: 'authentication-a4bc6',
    authDomain: 'authentication-a4bc6.firebaseapp.com',
    storageBucket: 'authentication-a4bc6.firebasestorage.app',
    measurementId: 'G-CG10MRR58T',
  );
}
